[project]
name = "skycord"
description = "An easy-to-use extension for the Pycord library"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
keywords = ["discord", "pycord", "py-cord"]
authors = [
    { name = "svtano" }
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dynamic = ["dependencies", "optional-dependencies", "version"]

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}
version = {attr = "skycord.__version__"}

[tool.setuptools.dynamic.optional-dependencies]
docs = {file = "docs/requirements.txt"}
dev = {file = "dev-requirements.txt"}

[project.urls]
GitHub = "https://github.com/tibue99/skycord"
Documentation = "https://skycord.readthedocs.io"

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"
